version: '3'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
  cpu:
    build: cpu/.
    ports:
      - "5000:5000"
    volumes:
      - ./cpu:/code
  frontend:
    build: frontend/.
    ports:
      - '81:80'
    volumes: 
      - ./frontend:/app/.
    links:
      - server
      - cpu
volumes:
  bundle:
  postgres-data:
